Major changes to model, agent, train.py added
I had errors in the action method of the agent. Led to AttributeError: 'numpy.int64' object has no attribute 'keys'